# Generated by Django 3.2.7 on 2021-10-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=3)),
                ('length_coat', models.IntegerField()),
                ('body_type', models.CharField(max_length=50)),
                ('pattern', models.CharField(max_length=50)),
            ],
        ),
    ]
